---

version: 1
formatters:
  simple:
    format: '%(asctime)s %(name)s [%(levelname)s] %(message)s'
  complex:
    format: '%(asctime)s %(name)s [%(levelname)s] %(message)s at %(funcName)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  console_complex:
    class: logging.StreamHandler
    level: DEBUG
    formatter: complex
    stream: ext://sys.stdout
loggers:
  RL866.state:
    level: DEBUG
    handlers: [console_complex]
    propagate: no
root:
  level: DEBUG
  handlers: [console]

