---

dateformat: '%d.%m.%Y'
devices:
  barcode-reader:
    enabled: true
    model: WGI3220USB
  rfid-reader:
    afi-checkin: 7
    afi-checkout: 194
    eas: true
    enabled: true
    iso28560-data-format-overloads:
    - '!class': ISO28560_3_Object
      dsfid: 0
    password: ''
    polling_interval: 1
  ringtone-player:
    enabled: false
  thermal-printer:
    enabled: true
    font-size: 12px
koha:
  api_memoize_cache_size: 8
  baseurl: https://demo1.intra.koha-helsinki-2.hypernova.fi
  branchcode: TIEKI
  password: correct_credentials_password-!
  userid: l-t-dev-good
ringtones:
  error: ToveriAccessDenied:d=4,o=4,b=100:32e,32d,32e,4c
  success: ToveriAccessGranted:d=4,o=5,b=100:32c5,32b4,32c5,4d5
server:
  hostname: localhost
  port: 53153
  timeout_request_connect_ms: 1000
  timeout_request_read_ms: 11000
ui:
  default_language: fi
  use_bookcovers: true

