devices:
  barcode-reader:
    enabled: true
    model: WGI3220USB
  rfid-reader:
    afi-checkin: 7
    afi-checkout: 194
    eas: false
    enabled: true
    iso28560-data-format-overloads:
    - '!class': ISO28560_3_Object
      dsfid: 0
    password: ''
    polling_interval: 0.25
  ringtone-player:
    enabled: false
  thermal-printer:
    check-in-receipt: /templates/check_in.j2
    check-out-receipt: koha
    css:
      font-family: Quicksand, sans-serif !important
      font-size: 12px
    css_string: ''
    enabled: true
i18n:
  default_locale: fi
  enabled_locales:
  - en
  - fi
  - ru
  - sv
  messages:
    fi:
      CheckIn:
        Place_to_bin_1: "Aseta hyllyyn selk\xE4si taakse"
        Place_to_bin_2: "Laita laatikkoon vieress\xE4si"
koha:
  api_memoize_cache_size: 8
  baseurl: https://demo1.intra.koha-helsinki-2.hypernova.fi
  branchcode: TIEKI
  password: correct_credentials_password-!
  timeout_request_connect_ms: 2500
  timeout_request_read_ms: 11000
  userid: l-t-dev-good
ringtones:
  error: ToveriAccessDenied:d=4,o=4,b=100:32e,32d,32e,4c
  success: ToveriAccessGranted:d=4,o=5,b=100:32c5,32b4,32c5,4d5
server:
  hostname: localhost
  port: 53153
ui:
  images:
  - position: Place_to_bin_1.png
    src: Place_to_bin_1.png
  - position: Place_to_bin_2.png
    src: Place_to_bin_2.png
  use_bookcovers: true
