devices:
  barcode-reader:
    enabled: true
    model: WGI3220USB
  rfid-reader:
    afi-checkin: 7
    afi-checkout: 194
    eas: false
    enabled: true
    iso28560-data-format-overloads:
    - '!class': ISO28560_3_Object
      dsfid: 0
    password: ''
    polling_interval: 0.25
  ringtone-player:
    enabled: false
    ringtone_types:
      checkin-error: ToveriAccessDenied
      checkin-success: ToveriAccessGranted
      checkout-error: ToveriAccessDenied:d=4,o=4,b=100:32e,32d,32e,4c
      checkout-success: ToveriAccessGranted:d=4,o=5,b=100:32c5,32b4,32c5,4d5
  thermal-printer:
    check-in-receipt: ./templates/check_in.j2
    check-in-receipt-koha-borrower: 0
    check-out-receipt: koha
    css:
      font-family: Quicksand, sans-serif !important
      font-size: 12px
    css_string: ''
    enabled: true
i18n:
  default_locale: fi
  enabled_locales:
  - en
  - fi
  - ru
  - sv
  messages:
    fi:
      CheckIn:
        Place_to_bin_ODD: "Aseta hyllyyn selk\xE4si taakse"
        Place_to_bin_OK: "Laita laatikkoon vieress\xE4si"
      MainMenuView:
        RFID_tags_found: "Aineisto l\xF6ydetty"
koha:
  api_memoize_cache_size: 8
  baseurl: https://demo1.intra.koha-helsinki-2.hypernova.fi
  branchcode: TIEKI
  password: correct_credentials_password-!
  timeout_request_connect_ms: 2500
  timeout_request_read_ms: 11000
  userid: l-t-dev-good
server:
  hostname: localhost
  port: 53153
ui:
  images:
  - position: Place_to_bin_OK
    src: Place_to_bin_OK.png
  - position: Place_to_bin_ODD
    src: Place_to_bin_ODD.png
  - position: logo-big
    src: ../../../lainuri-ui/public/images/shared_gallery/xamk-logo-big.png
  - position: logo-small
    src: ../../../lainuri-ui/public/images/shared_gallery/xamk-logo-small.png
  use_bookcovers: true
