---

version: 1
formatters:
  raw:
    format: '%(message)s'
  simple:
    format: '%(asctime)s %(name)s [%(levelname)s] %(message)s'
  colored:
    class: colorlog.ColoredFormatter
    format: '%(log_color)s%(asctime)s %(name)s [%(levelname)s]%(reset)s %(message)s at %(funcName)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
  console_complex:
    class: logging.StreamHandler
    formatter: colored
    stream: ext://sys.stdout
  scraper:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: colored
    filename: {lainuri_log_dir}/scraper.log
    when: 'D'
  external_log:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: raw
    filename: {lainuri_log_dir}/external.log
    when: 'D'
loggers:
  lainuri.websocket_handlers.logging_external:
    level: DEBUG
    handlers: [external_log]
    propagate: no
  lainuri.scraping:
    level: DEBUG
    handlers: [scraper]
    propagate: no
  lainuri.rfid_reader:
    level: INFO
    handlers: [console_complex]
    propagate: no
  lainuri.RL866:
    level: INFO
    handlers: [console_complex]
    propagate: no
  root:
    level: ERROR
    handlers: [console]
